/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica se a API está no ar */
        get: operations["verificar_saude_api_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Importa um arquivo de dados */
        post: operations["importar_api_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/exemplo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Importa o arquivo de exemplo (pesquisa_saude.txt) */
        post: operations["importar_exemplo_api_datasets_exemplo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/leitura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lê de novo o arquivo com outras opções */
        post: operations["reler_api_datasets__dataset_id__leitura_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumo do dataset e linhas paginadas */
        get: operations["obter_pagina_api_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Descarta o dataset */
        delete: operations["remover_api_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/colunas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tipo de cada coluna, com o motivo */
        get: operations["listar_colunas_api_datasets__dataset_id__colunas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/colunas/{coluna}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corrige o tipo de uma coluna */
        patch: operations["alterar_tipo_api_datasets__dataset_id__colunas__coluna__patch"];
        trace?: never;
    };
    "/api/datasets/{dataset_id}/diagnostico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problemas encontrados (não altera nada) */
        get: operations["diagnosticar_api_datasets__dataset_id__diagnostico_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/limpeza": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aplica ações de limpeza na versão atual */
        post: operations["limpar_api_datasets__dataset_id__limpeza_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/limpeza/desfazer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desfaz toda a limpeza */
        post: operations["desfazer_limpeza_api_datasets__dataset_id__limpeza_desfazer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/colunas/{coluna}/analise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Análise univariada da coluna (specs 04–07) */
        get: operations["analisar_api_datasets__dataset_id__colunas__coluna__analise_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/colunas/{coluna}/posicao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** "Onde está meu valor?" (spec 06) */
        get: operations["posicao_api_datasets__dataset_id__colunas__coluna__posicao_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset_id}/relatorio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mini relatório em HTML */
        get: operations["gerar_relatorio_api_datasets__dataset_id__relatorio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Acao: "manter" | "remover_linhas" | "preencher_media" | "preencher_mediana" | "preencher_moda" | "preencher_valor" | "remover" | "limitar" | "marcar_faltante" | "unificar";
        /** AcaoLimpeza */
        AcaoLimpeza: {
            problema: components["schemas"]["Problema"];
            acao: components["schemas"]["Acao"];
            /** Coluna */
            coluna?: string | null;
            valor?: components["schemas"]["Celula"];
            limites?: components["schemas"]["Limites"] | null;
            /** Grupo */
            grupo?: string | null;
        };
        /** AlteracaoTipo */
        AlteracaoTipo: {
            tipo: components["schemas"]["TipoVariavel"];
            /** Categorias Ordem */
            categorias_ordem?: string[] | null;
        };
        /** Analise */
        Analise: {
            /** Coluna */
            coluna: string;
            tipo: components["schemas"]["TipoVariavel"];
            /** N */
            n: number;
            /** N Faltantes */
            n_faltantes: number;
            /** Aplicavel */
            aplicavel: {
                [key: string]: boolean;
            };
            /** Nao Aplicavel */
            nao_aplicavel: components["schemas"]["NaoAplicavel"][];
            frequencias: components["schemas"]["TabelaFrequencia"];
            tendencia: components["schemas"]["Tendencia"];
            separatrizes: components["schemas"]["Separatrizes"] | null;
            dispersao: components["schemas"]["Dispersao"] | null;
            /** Interpretacoes */
            interpretacoes: string[];
            /** Formulas */
            formulas: components["schemas"]["Formula"][];
            /** Figuras */
            figuras: components["schemas"]["Figura"][];
        };
        /** Aviso */
        Aviso: {
            /** Codigo */
            codigo: string;
            /** Mensagem */
            mensagem: string;
        };
        /** Body_importar_api_datasets_post */
        Body_importar_api_datasets_post: {
            /** Arquivo */
            arquivo: string;
            /** Separador */
            separador?: string | null;
            /** Decimal */
            decimal?: ("," | ".") | null;
            /** Codificacao */
            codificacao?: string | null;
            /** Aba */
            aba?: string | null;
            /** Linha Cabecalho */
            linha_cabecalho?: number | null;
        };
        Celula: string | number | boolean | null;
        /** DatasetCriado */
        DatasetCriado: {
            /** Dataset Id */
            dataset_id: string;
            /** Nome Arquivo */
            nome_arquivo: string;
            metadados: components["schemas"]["MetadadosLeitura"];
            /** Previa */
            previa: components["schemas"]["LinhaDados"][];
            /** Colunas */
            colunas: components["schemas"]["TipoColuna"][];
        };
        /** Diagnostico */
        Diagnostico: {
            /** N Linhas */
            n_linhas: number;
            /** Faltantes */
            faltantes: components["schemas"]["FaltantesColuna"][];
            /** Duplicados */
            duplicados: components["schemas"]["GrupoDuplicado"][];
            /** Fora De Faixa */
            fora_de_faixa: components["schemas"]["ForaDeFaixaColuna"][];
            /** Inconsistencias */
            inconsistencias: components["schemas"]["InconsistenciaColuna"][];
            /** Tipo Misto */
            tipo_misto: components["schemas"]["TipoMistoColuna"][];
        };
        /** Dispersao */
        Dispersao: {
            amplitude: components["schemas"]["Medida"];
            variancia: components["schemas"]["Medida"];
            variancia_populacional: components["schemas"]["Medida"];
            desvio_padrao: components["schemas"]["Medida"];
            desvio_padrao_populacional: components["schemas"]["Medida"];
            iqr: components["schemas"]["Medida"];
            cv: components["schemas"]["Medida"];
            /** Classificacao Cv */
            classificacao_cv: ("baixa" | "media" | "alta") | null;
        };
        /** EntradaLog */
        EntradaLog: {
            /** Problema */
            problema: string;
            /** Acao */
            acao: string;
            /** Coluna */
            coluna: string | null;
            /** Linhas Afetadas */
            linhas_afetadas: number[];
            /** Antes Exemplo */
            antes_exemplo: string;
            /** Depois Exemplo */
            depois_exemplo: string;
            /**
             * Quando
             * Format: date-time
             */
            quando: string;
            /** Frase */
            frase: string;
        };
        /** FaltantesColuna */
        FaltantesColuna: {
            /** Coluna */
            coluna: string;
            /** N */
            n: number;
            /** Linhas */
            linhas: number[];
            sugeridos: components["schemas"]["ValoresSugeridos"];
        };
        /** Figura */
        Figura: {
            /** Id */
            id: string;
            /** Rotulo */
            rotulo: string;
            /** Titulo */
            titulo: string;
            /** Resumo */
            resumo: string;
            /** Porque */
            porque: string;
            /** Recomendado */
            recomendado: boolean;
            /** Dados */
            dados: {
                [key: string]: unknown;
            };
        };
        /** ForaDeFaixaColuna */
        ForaDeFaixaColuna: {
            /** Coluna */
            coluna: string;
            /** Limite Inferior */
            limite_inferior: number;
            /** Limite Superior */
            limite_superior: number;
            /**
             * Origem
             * @enum {string}
             */
            origem: "iqr" | "usuario";
            /** Ocorrencias */
            ocorrencias: components["schemas"]["Ocorrencia"][];
        };
        /** Formula */
        Formula: {
            /** Chave */
            chave: string;
            /** Nome */
            nome: string;
            /** Latex */
            latex: string;
            /** Texto */
            texto: string;
        };
        /** Grafia */
        Grafia: {
            /** Texto */
            texto: string;
            /** N */
            n: number;
        };
        /** GrupoDuplicado */
        GrupoDuplicado: {
            /** Linha Original */
            linha_original: number;
            /** Copias */
            copias: number[];
        };
        /** GrupoGrafias */
        GrupoGrafias: {
            /** Forma Preferida */
            forma_preferida: string;
            /** Variacoes */
            variacoes: components["schemas"]["Grafia"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InconsistenciaColuna */
        InconsistenciaColuna: {
            /** Coluna */
            coluna: string;
            /** Grupos */
            grupos: components["schemas"]["GrupoGrafias"][];
        };
        /** Limites */
        Limites: {
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /** LinhaArquivo */
        LinhaArquivo: {
            /** Numero */
            numero: number;
            /** Celulas */
            celulas: string[];
        };
        /** LinhaDados */
        LinhaDados: {
            /** Linha */
            linha: number;
            /** Valores */
            valores: {
                [key: string]: components["schemas"]["Celula"];
            };
        };
        /** LinhaFrequencia */
        LinhaFrequencia: {
            /** Rotulo */
            rotulo: string;
            valor: components["schemas"]["Valor"];
            /** Limite Inferior */
            limite_inferior: number | null;
            /** Limite Superior */
            limite_superior: number | null;
            /** Ponto Medio */
            ponto_medio: number | null;
            /** Fi */
            fi: number;
            /** Fri */
            fri: number;
            /** Fr Pct */
            fr_pct: number;
            /** F Acum */
            f_acum: number | null;
            /** Fr Acum */
            fr_acum: number | null;
            /** Fr Acum Pct */
            fr_acum_pct: number | null;
        };
        /** Medida */
        Medida: {
            valor: components["schemas"]["Valor"];
            /** Aplicavel */
            aplicavel: boolean;
            /** Motivo */
            motivo: string | null;
            /** Calculo */
            calculo: string | null;
            /** Interpretacao */
            interpretacao: string | null;
            /** Formula */
            formula: string | null;
        };
        /** MetadadosLeitura */
        MetadadosLeitura: {
            /**
             * Formato
             * @enum {string}
             */
            formato: "txt" | "csv" | "tsv" | "xlsx" | "json";
            /** Codificacao */
            codificacao: string | null;
            /** Separador */
            separador: string | null;
            /** Decimal */
            decimal: string | null;
            /** Linha Cabecalho */
            linha_cabecalho: number | null;
            /** N Linhas */
            n_linhas: number;
            /** N Colunas */
            n_colunas: number;
            /** Abas */
            abas: string[];
            /** Avisos */
            avisos: components["schemas"]["Aviso"][];
            /** Motivos */
            motivos: {
                [key: string]: string;
            };
            /** Linhas Iniciais */
            linhas_iniciais: components["schemas"]["LinhaArquivo"][];
        };
        /** Moda */
        Moda: {
            /** Valores */
            valores: (number | string)[];
            /**
             * Classificacao
             * @enum {string}
             */
            classificacao: "amodal" | "unimodal" | "bimodal" | "multimodal";
            /** Interpretacao */
            interpretacao: string;
        };
        /** NaoAplicavel */
        NaoAplicavel: {
            /** Item */
            item: string;
            /** Motivo */
            motivo: string;
        };
        /** Ocorrencia */
        Ocorrencia: {
            /** Linha */
            linha: number;
            valor: components["schemas"]["Celula"];
        };
        /**
         * OrigemTipo
         * @description Quem definiu o tipo: a classificação automática ou o usuário.
         * @enum {string}
         */
        OrigemTipo: "auto" | "manual";
        /** PaginaDataset */
        PaginaDataset: {
            resumo: components["schemas"]["ResumoDataset"];
            /**
             * Versao
             * @enum {string}
             */
            versao: "atual" | "original";
            /** Pagina */
            pagina: number;
            /** Tamanho */
            tamanho: number;
            /** Total Paginas */
            total_paginas: number;
            /** Linhas */
            linhas: components["schemas"]["LinhaDados"][];
        };
        /**
         * PedidoLeitura
         * @description Opções que sobrescrevem a detecção; vazio = detectar tudo de novo (spec 01).
         */
        PedidoLeitura: {
            /** Separador */
            separador?: string | null;
            /** Decimal */
            decimal?: ("," | ".") | null;
            /** Codificacao */
            codificacao?: string | null;
            /** Aba */
            aba?: string | null;
            /** Linha Cabecalho */
            linha_cabecalho?: number | null;
        };
        /** PedidoLimpeza */
        PedidoLimpeza: {
            /** Acoes */
            acoes: components["schemas"]["AcaoLimpeza"][];
        };
        /** Posicao */
        Posicao: {
            /** Valor */
            valor: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "quartil" | "decil" | "percentil";
            /** Regiao */
            regiao: string;
            /** Indice */
            indice: number;
            /** Limite Inferior */
            limite_inferior: number | null;
            /** Limite Superior */
            limite_superior: number | null;
            /** Posicao Percentil */
            posicao_percentil: number;
            /** Fora Da Faixa */
            fora_da_faixa: ("abaixo" | "acima") | null;
            /** Minimo */
            minimo: number;
            /** Maximo */
            maximo: number;
            /** Marcas */
            marcas: components["schemas"]["ValorSeparatriz"][];
            /** Frase */
            frase: string;
        };
        /** @enum {string} */
        Problema: "faltantes" | "duplicados" | "fora_de_faixa" | "inconsistencia" | "tipo_misto";
        /** ResultadoLimpeza */
        ResultadoLimpeza: {
            /** Log */
            log: components["schemas"]["EntradaLog"][];
            /** N Linhas */
            n_linhas: number;
            /** N Linhas Original */
            n_linhas_original: number;
            /** Colunas */
            colunas: components["schemas"]["TipoColuna"][];
        };
        /** ResumoDataset */
        ResumoDataset: {
            /** Dataset Id */
            dataset_id: string;
            /** Nome Arquivo */
            nome_arquivo: string;
            metadados: components["schemas"]["MetadadosLeitura"];
            /** N Linhas */
            n_linhas: number;
            /** N Linhas Original */
            n_linhas_original: number;
            /** N Colunas */
            n_colunas: number;
            /** Log Limpeza */
            log_limpeza: components["schemas"]["EntradaLog"][];
            opcoes_leitura: components["schemas"]["PedidoLeitura"];
            /** Tem Ajustes */
            tem_ajustes: boolean;
        };
        /** Saude */
        Saude: {
            /** Status */
            status: string;
            /** Versao */
            versao: string;
        };
        /** @enum {string} */
        Secao: "leitura" | "tipos" | "limpeza" | "analises";
        /** Separatrizes */
        Separatrizes: {
            /** Quartis */
            quartis: components["schemas"]["ValorSeparatriz"][];
            /** Decis */
            decis: components["schemas"]["ValorSeparatriz"][];
            /** Percentis */
            percentis: components["schemas"]["ValorSeparatriz"][];
            /** Destaques */
            destaques: string[];
        };
        /** TabelaFrequencia */
        TabelaFrequencia: {
            tipo: components["schemas"]["TipoVariavel"];
            /** Linhas */
            linhas: components["schemas"]["LinhaFrequencia"][];
            /** Total */
            total: number;
            /** K */
            k: number | null;
            /** K Sturges */
            k_sturges: number | null;
            /** H */
            h: number | null;
            /** Metodo Classes */
            metodo_classes: ("sturges" | "usuario") | null;
            /** Acumulada Aplicavel */
            acumulada_aplicavel: boolean;
            /** Motivo Acumulada */
            motivo_acumulada: string | null;
            /** Indice Modal */
            indice_modal: number | null;
        };
        /** Tendencia */
        Tendencia: {
            media: components["schemas"]["Medida"];
            mediana: components["schemas"]["Medida"];
            moda: components["schemas"]["Moda"];
            moda_czuber: components["schemas"]["Medida"];
            proporcao: components["schemas"]["Medida"];
        };
        /** TipoColuna */
        TipoColuna: {
            /** Coluna */
            coluna: string;
            tipo: components["schemas"]["TipoVariavel"];
            /** Motivo */
            motivo: string;
            origem: components["schemas"]["OrigemTipo"];
            /** N Validos */
            n_validos: number;
            /** N Faltantes */
            n_faltantes: number;
            /** N Distintos */
            n_distintos: number;
            /** Exemplos */
            exemplos: string[];
            /** Categorias Ordem */
            categorias_ordem: string[];
            /** Contagens */
            contagens: {
                [key: string]: number;
            };
        };
        /** TipoMistoColuna */
        TipoMistoColuna: {
            /** Coluna */
            coluna: string;
            /** Ocorrencias */
            ocorrencias: components["schemas"]["Ocorrencia"][];
        };
        /**
         * TipoVariavel
         * @description Tipos de variável da spec 02 (identificador é auxiliar e fica fora das análises).
         * @enum {string}
         */
        TipoVariavel: "nominal" | "ordinal" | "discreta" | "continua" | "binaria" | "identificador";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        Valor: number | string | null;
        /** ValorSeparatriz */
        ValorSeparatriz: {
            /** Rotulo */
            rotulo: string;
            /** P */
            p: number;
            /** Valor */
            valor: number | string;
        };
        /** ValoresSugeridos */
        ValoresSugeridos: {
            /** Media */
            media: number | null;
            /** Mediana */
            mediana: number | null;
            moda: components["schemas"]["Celula"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verificar_saude_api_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
    importar_api_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importar_api_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetCriado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importar_exemplo_api_datasets_exemplo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetCriado"];
                };
            };
        };
    };
    reler_api_datasets__dataset_id__leitura_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoLeitura"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetCriado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_pagina_api_datasets__dataset_id__get: {
        parameters: {
            query?: {
                pagina?: number;
                tamanho?: number;
                versao?: "atual" | "original";
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remover_api_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_colunas_api_datasets__dataset_id__colunas_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoColuna"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alterar_tipo_api_datasets__dataset_id__colunas__coluna__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                coluna: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlteracaoTipo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoColuna"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnosticar_api_datasets__dataset_id__diagnostico_get: {
        parameters: {
            query?: {
                /** @description Limites por coluna em JSON: {"idade": {"min": 1, "max": 110}} */
                limites?: string | null;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostico"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    limpar_api_datasets__dataset_id__limpeza_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoLimpeza"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoLimpeza"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desfazer_limpeza_api_datasets__dataset_id__limpeza_desfazer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoLimpeza"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analisar_api_datasets__dataset_id__colunas__coluna__analise_get: {
        parameters: {
            query?: {
                classes?: number | null;
                /** @description Categoria de sucesso (binária) */
                sucesso?: string | null;
            };
            header?: never;
            path: {
                dataset_id: string;
                coluna: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analise"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    posicao_api_datasets__dataset_id__colunas__coluna__posicao_get: {
        parameters: {
            query: {
                valor: number;
                tipo?: "quartil" | "decil" | "percentil";
            };
            header?: never;
            path: {
                dataset_id: string;
                coluna: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Posicao"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gerar_relatorio_api_datasets__dataset_id__relatorio_get: {
        parameters: {
            query?: {
                /** @description Seções do mini relatório */
                secoes?: components["schemas"]["Secao"][] | null;
                /** @description Colunas analisadas */
                colunas?: string[] | null;
                /** @description Embute o plotly.js (funciona sem internet) */
                offline?: boolean;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
